Repository OFU-Crew/dear-world-iOS, pull requests merged in 2020-12, with the labels that each got.

#3 ✨ 기본 ViewController 구현
  Dear-World/Dear-World.xcodeproj/project.pbxproj
  Dear-World/Dear-World/Source/Presentation/Scene/About/AboutViewController.swift
  Dear-World/Dear-World/Source/Presentation/Scene/Cheering Map/CheeringMapViewController.swift
  Dear-World/Dear-World/Source/Presentation/Scene/Send Message/SendMessageViewController.swift
Labels: ✍️ in review

#4 Feature/message count badge view
  Dear-World/.swiftlint.yml
  Dear-World/Dear-World.xcodeproj/MessageCountBadgeView.swift
  Dear-World/Dear-World.xcodeproj/project.pbxproj
  Dear-World/Dear-World/Source/Presentation/Scene/Discover/Discover.storyboard
  Dear-World/Dear-World/Source/Presentation/Scene/Discover/DiscoverViewController.swift
Labels: 🙆‍♂️ merge needed

#5 💄 UIColor 익스텐션 파일 생성
  Dear-World/Dear-World.xcodeproj/project.pbxproj
  Dear-World/Dear-World/Resource/Colors.xcassets/loveRed.colorset/Contents.json
  Dear-World/Dear-World/Source/Common/UIColor.swift
  Dear-World/Dear-World/Source/Presentation/Scene/Discover/DiscoverViewController.swift
Labels: 🙆‍♂️ merge needed

#6 💄 CountryTableViewCell UI 구현
  Dear-World/.swiftlint.yml
  Dear-World/Dear-World.xcodeproj/project.pbxproj
  Dear-World/Dear-World.xcodeproj/project.xcworkspace/contents.xcworkspacedata~Stashed changes
  Dear-World/Dear-World.xcodeproj/project.xcworkspace/contents.xcworkspacedata~Updated upstream
  Dear-World/Dear-World/Resource/Assets.xcassets/message_default.imageset/Contents.json
  Dear-World/Dear-World/Resource/Assets.xcassets/message_default.imageset/message_default.pdf
  Dear-World/Dear-World/Source/Common/Extension/Int+.swift
  Dear-World/Dear-World/Source/Common/Extension/UIColor+.swift
  Dear-World/Dear-World/Source/Presentation/Scene/Cheering Map/Cell/CountryTableViewCell.swift
  Dear-World/Dear-World/Source/Presentation/Scene/Cheering Map/CheeringMapViewController.swift
  Dear-World/Dear-World/Source/Presentation/Scene/Discover/DiscoverViewController.swift
Labels: ✨ enhancement

#9 :lipstick: 하트 애니메이션 추가
  Dear-World/Dear-World.xcodeproj/MessageCountBadgeView.swift
  Dear-World/Dear-World.xcodeproj/project.pbxproj
  Dear-World/Dear-World/Source/Common/Extension/UIControl+Rx.swift
  Dear-World/Dear-World/Source/Common/Extension/UIImage+.swift
  Dear-World/Dear-World/Source/Common/Extension/UIView+.swift
  Dear-World/Dear-World/Source/Presentation/Scene/Cheering Map/Cell/CountryTableViewCell.swift
  Dear-World/Dear-World/Source/Presentation/Scene/Cheering Map/CheeringMapViewController.swift
  Dear-World/Dear-World/Source/Presentation/View/CheerButton.swift
Labels: ✨ enhancement
